language: php

dist: trusty
sudo: required

php:
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - ./install.sh

script:
  - vendor/bin/phpunit --coverage-text tests
